### ISSUE TITLE
OpenSCAD design files?

### ISSUE THREAD

**Issue by tlaurion** [apollo-ng/seedstack#2]
Hey @chron0 
Wrote a comment on your website. I would be interested in having the openscad scripts to generate the container and the siphon to be a little longer. Would also modify the container for the cracks to be thinner but taller, so that greek fenu don't fall in the cracks. Would also modify/create the a container base to receive the water.

Thanks for your work! Near to perfect!

**Comment by tlaurion** [comment]
Found them in the archive here https://www.thingiverse.com/thing:766711/

**Comment by chron0** [comment]
Also in https://github.com/apollo-ng/seedstack/tree/master/model
